### ISSUE TITLE
Bloquear master?

### ISSUE THREAD

**Issue by giovana-morais** [caccs/Manual-do-Bixo#23]
estive pensando aqui em forçamos o pull request pra todo mundo conseguir validar e etc, além de forçar todo mundo a aprender a usar o git sem acabar estragando algo na master. 
@eiguike  @Darkkgreen vocês sabem se a nossa ```master``` é bloqueada?

**Comment by eiguike** [comment]
Aparentemente a branch `master` já estava bloqueada, adicionei alguns requisitos do CI e de forçar essa regra para gente também, hahaha.

**Comment by giovana-morais** [comment]
🔝 🔝 🔝 🔝 🔝 🔝 
vou encerrar isso aqui então
